/*
 * do-work-dispatch.core.js — Dynamic Workflows scaffold for /shipyard:do-work
 * =============================================================================
 *
 * THIS FILE IS A SOURCE FRAGMENT, NOT THE RUNTIME SCRIPT (issue #958)
 * ---------------------------------------------------------------------------
 * `workflows/do-work-dispatch.workflow.js` — the single flat literal the
 * Dynamic Workflows runtime actually executes — is GENERATED by concatenating
 * this file (the orchestration logic: `meta`, `args` handling, the
 * select/dispatch/collect stages, `unitLabel`, and the `buildWorkerPrompt`
 * mode-routing switch) with the seven per-mode dispatch-prompt builders and
 * their shared worktree-anchor helpers, which live as their own small,
 * independently-editable ES modules under `workflows/prompt-templates/`
 * (`shared.mjs`, `issue-work.mjs`, `fix-checks-only.mjs`, `fix-rebase.mjs`,
 * `fix-main-ci.mjs`, `fix-failing-prs-batch.mjs`, `investigate.mjs`,
 * `spike.mjs`). Those seven builders used to live inline in this file — at
 * ~469 lines they were the bulk of its size and none of it was orchestration
 * logic, which made the file harder to read/maintain than the ~500 lines of
 * actual dispatch-loop logic warranted. A source-level `import`/`require`
 * split is NOT possible for the RUNTIME file: the Dynamic Workflows runtime
 * executes it in an isolated sandbox with no filesystem access of its own
 * (see the "Worktree isolation" section below for the identical constraint
 * applied to worker dispatch, and `workerReturnSchema`'s own comment for the
 * same constraint applied to schema mirroring) — so the runtime file must
 * stay one self-contained literal. The generator
 * (`scripts/generate-dispatch-workflow.mjs`) is what reconciles "split for
 * editability" with "flat for runtime execution": it reads this file plus
 * the `prompt-templates/*.mjs` fragments, strips their `import`/`export`
 * syntax, and concatenates the result into `do-work-dispatch.workflow.js`,
 * which stays checked into git as the generated artifact (exactly as this
 * issue's own suggested approach describes). `scripts/tests/
 * dispatch-workflow-generated-958.test.sh` fails CI if the checked-in
 * generated file has drifted from what regenerating these sources produces —
 * so a hand-edit applied directly to the generated file (instead of here, or
 * instead of a `prompt-templates/*.mjs` fragment) is caught mechanically, not
 * silently accepted on the next PR.
 *
 * TO REGENERATE after editing this file or any `prompt-templates/*.mjs`:
 *
 *   node plugins/shipyard/scripts/generate-dispatch-workflow.mjs
 *
 * Everything below this note is the SAME orchestration-logic content that
 * lived at the top of `do-work-dispatch.workflow.js` before #958 — the
 * historical narrative, the runtime-API notes, the `meta`-must-be-a-pure-
 * literal constraint, and the `args`-must-fail-loudly contract are all
 * unchanged and still apply to the generated file this fragment produces.
 * =============================================================================
 *
 * The #782 epic's five-phase migration (#787-#791, completing with a 3.x ->
 * 4.0.0 major bump) made this script the SOLE dispatch substrate for all seven
 * `mode:`-driven workers, retiring the hand-rolled `Agent`-tool orchestrator
 * entirely — full phase-by-phase history in commands/do-work-RATIONALE.md's
 * "Why two dispatch shapes exist" section. #825 THEN PARTIALLY REVERTED THAT:
 * this substrate's dispatched workers could not perform a single file write
 * (the harness refused every Edit/Write call with a "parent bg session hasn't
 * isolated" error), so #825 restored the `Agent`-tool dispatch shape as the
 * DEFAULT for `mode:`-driven workers — WITHOUT reintroducing the
 * `dispatch.substrate` knob #791 deleted. See dispatch-rules.md's "Agent-tool
 * dispatch" (default) and "Workflow-substrate dispatch" (alternate) sections
 * for the current split and the full per-mode call-site walkthrough of this
 * script.
 *
 * STATUS as of #825:
 *   - This script is an ALTERNATE way a `mode:`-driven /do-work worker can be
 *     dispatched — the DEFAULT is the `Agent` tool (`subagent_type` + isolation:
 *     "worktree"), per dispatch-rules.md. There is still no config flag choosing
 *     between the two shapes; the choice is spec-level, not user-configurable.
 *   - The `Agent` tool is also used elsewhere in shipyard (shipyard:verify-worker
 *     with isolation: "worktree", shipyard:decompose-worker, the read-only scope-
 *     preflight / refinement workers) — none of those take a `mode:` value, and
 *     none route through here.
 *
 * WHY SCAFFOLD IT NOW. Moving the dispatch plan "into code" is the durable win the
 * epic is after: zero routing-token overhead, fixed cost/latency, and an auditable
 * topology (declared, diffable, reviewable — like infrastructure-as-code). shipyard's
 * do-work topology (select → dispatch → verify → merge, with blocked-by sequencing)
 * is exactly a known-shape workflow. Committing the shape first lets each subsequent
 * phase migrate one mode against a stable target instead of designing the substrate
 * and the migration in the same PR.
 *
 * RUNTIME API used here (Claude Code Dynamic Workflows — code.claude.com/docs/en/workflows):
 *   - `export const meta = { name, description }` — the saved-workflow header.
 *   - top-level `await` — the body is plain JavaScript.
 *   - `agent(prompt, opts)` — spawn ONE subagent. `opts.schema` validates its
 *     structured return (pointed at `workerReturnSchema` below, a same-shape copy
 *     of schemas/worker-return.schema.json); `opts.label` names it in the
 *     /workflows progress view; `opts.model` routes the stage to a specific model
 *     (the family alias — `opus`/`sonnet`/`haiku`/`fable` — that
 *     `resolve-dispatch-model.sh` resolves from the merged config's
 *     `models.<mode>` key and the caller passes in as `unit.model`).
 *   - `args` — global carrying invocation input: one work unit per `agent()` call.
 *
 * The runtime also exposes `pipeline(list, fn)` and `parallel(tasks, opts)`
 * fan-out primitives (a bounded-concurrency pool, capped at 16 agents / 1,000
 * agents-per-run regardless of what a caller requests — see the docs "Behavior
 * and limits" table), but THIS SCRIPT DOES NOT CALL EITHER (issue #888). An
 * earlier revision kept an unused `parallel()`/`pipeline()` selection branch as
 * scaffolding for a hypothetical future batch-dispatch phase; it was deleted
 * rather than left dormant — see "Concurrency model" below for why, and the
 * issue #888 decision comment for the full reasoning (in short: `parallel()`'s
 * option surface is still not fully public as of this writing, so pinning
 * behavior on an untested API ahead of a real need was a liability, not free
 * insurance; recovering the deleted branch from git history is cheaper than
 * carrying an unexercised one). If a genuine multi-unit batch need ever
 * materializes, re-add fan-out then, against a stable option surface.
 *
 * Concurrency model (all modes)
 * ----------------------------------------
 * The orchestrator's `--concurrency N` rolling worker pool (steady-state.md step C
 * / setup.md step 7) is what bounds parallelism — not this script. Each pool slot
 * corresponds to exactly one dispatch: filling a slot for ANY mode invokes the
 * `Workflow` tool against this script with ONE work unit in `args.issues`, and
 * this script dispatches it with a single `agent()` call and returns. There is
 * no in-script fan-out layer coordinating with the orchestrator's pool — the
 * pool IS the sole concurrency mechanism, for every mode, full stop. See
 * dispatch-rules.md's substrate section for the full call-site walkthrough
 * (pre-provisioning the worktree, building `args`, translating the structured
 * return back into the free-text vocabulary steady-state.md's step A.1 already
 * parses).
 *
 * Worktree isolation (all modes) — GENUINE GAP, closed by the caller
 * -------------------------------------------------------------------------------
 * The `Agent` tool's `isolation: "worktree"` parameter has the harness
 * auto-provision and cwd-pin an isolated worktree for the dispatched subagent
 * before it runs a single tool call — that's how the DEFAULT `Agent`-tool shape
 * gets isolation for free (see the file-header #825 note above). THIS script's
 * `Workflow` substrate has no equivalent primitive: as of this writing, the
 * Dynamic Workflows docs (code.claude.com/docs/en/workflows) document NO
 * isolation option on `agent()` at all — the docs state plainly that "the
 * workflow [script] itself" has no filesystem/shell access ("Agents read,
 * write, and run commands. The script coordinates the agents") and describe
 * `agent()`'s options only as prompt/label/model/schema; there is no isolation,
 * worktree, or sandboxing field in that surface. This script therefore CANNOT
 * auto-provision worker isolation the way the `Agent`-tool path does — that
 * responsibility sits with the CALLER (the orchestrator session, which still
 * has full shell access, unlike this script):
 *   1. Before invoking this script, the orchestrator provisions the isolated
 *      worktree itself and passes the resulting absolute path as
 *      `unit.worktreePath`. The exact git-worktree invocation depends on the
 *      mode's branch shape:
 *        - `issue-work` / `investigate` / `spike`: `git worktree add <path> -b
 *          do-work/issue-<N> origin/<default-branch>` — a fresh branch off
 *          default (what the `Agent`-tool path's `isolation: "worktree"`
 *          produces for these modes).
 *        - `fix-checks-only` / `fix-rebase`: `git worktree add <path> -B
 *          <headRefName> origin/<headRefName>` — checked out directly onto the
 *          EXISTING PR branch being fixed/rebased, not a fresh branch off
 *          default. This mirrors what fix-checks-only.md's own Setup step
 *          (`git fetch origin "$HEAD_REF" && git switch "$HEAD_REF"`) would have
 *          done inside an `Agent`-tool `isolation: "worktree"` dispatch's
 *          placeholder worktree — pre-provisioning it this way makes that fetch/
 *          switch step a no-op safety net rather than required additional setup.
 *        - `fix-main-ci` / `fix-failing-prs-batch`: `git worktree add <path> -b
 *          do-work/fix-main-ci-<short-sha>` / `do-work/fix-pr-pileup-<timestamp>
 *          origin/<default-branch>` — synthetic-divert branch naming, same
 *          fresh-off-default shape as issue-work.
 *   2. Every per-mode prompt builder below makes the worker's FIRST instruction
 *      an explicit `cd`/anchor into that path (via the shared `worktreeAnchorLines`
 *      helper). This is Rule 0 of `shipyard:worker-preamble` § "Worktree
 *      discipline": a Workflow-dispatched worker's cwd is NOT pre-pinned, so it
 *      must anchor itself before doing anything else, and only THEN does the
 *      "never cd outside your worktree" rule take effect.
 *   3. The worker then re-applies the SAME step-0 fail-fast verification
 *      (`shipyard:worker-preamble` § "Step-0 cwd fail-fast") to confirm the `cd`
 *      landed on an isolated worktree (git-dir != git-common-dir) rather than
 *      trusting the `cd` succeeded silently — this check is substrate-agnostic
 *      and transfers unmodified.
 * This is documented in full in dispatch-rules.md's substrate section; it is
 * called out here too because it is the single largest behavioral difference
 * between the two substrates and easy to miss if only one of the two files is read.
 *
 * WHAT STAYS OUT OF THIS SCRIPT (shipyard's durable policy edge, kept as the
 * workflow's control flow / injected via `args`, NOT re-derived here):
 *   - WHICH issues/PRs/diverts to pick (backlog fetch + gate-label exclusion +
 *     author trust + blocked-by sequencing + divert-queue priority + collision
 *     tiering) — commands/do-work/setup/* + dispatch-rules.md.
 *   - Priority scoring, path-collision tiering, phase-1 slice augmentation, the
 *     verify-gate opt-in, the user-feedback extra-scrutiny preamble, the
 *     triage.auto_close policy, the decompose.max_subissues fan-out cap, and
 *     next-available-version coordination — all computed by the orchestrator
 *     exactly as they are for the `Agent`-tool path, then passed through
 *     `args.issues[]` fields consumed by the per-mode builders below.
 *   - Worktree provisioning, per-mode model resolution, version coordination — the
 *     orchestrator computes/performs these and passes the results in.
 * The script's job is the ORCHESTRATION shape (select → dispatch → collect), not
 * the policy. That division is what no native tool provides and what the epic keeps.
 *
 * `export const meta` MUST BE A PURE LITERAL (issue #809)
 * -------------------------------------------------------------------------------
 * The `Workflow` tool validates `meta` at the TOOL-CALL BOUNDARY, before the script
 * ever runs, and rejects the whole script unless every node inside the `meta` object
 * is a literal: no variables, no function calls, no spreads, no template
 * interpolation — and, the trap that actually shipped, NO STRING CONCATENATION.
 * `'a' + 'b'` is a `BinaryExpression`, not a literal, so a `description` assembled
 * from `+`-joined fragments fails with:
 *
 *   Invalid workflow script: meta must be a pure literal:
 *   non-literal node type in meta: BinaryExpression
 *
 * `node --check` PASSES on that form — the concatenation is perfectly valid
 * JavaScript — which is exactly why 4.0.0 through 4.0.3 shipped with every dispatch
 * broken and no CI signal. `scripts/tests/workflow-meta-pure-literal-809.test.sh`
 * now walks `meta` as an AST and fails on any non-literal node, so the regression
 * cannot reappear silently.
 *
 * PRACTICAL CONSEQUENCE: `meta.description` must be ONE single-quoted string
 * literal on one line, however long. Do not wrap it across lines with `+`, do not
 * switch it to a backtick template, do not build it from a helper. Long-form prose
 * belongs in THIS header comment, which is unconstrained — and the description
 * itself should stay short anyway, since it renders in the permission dialog and
 * the /workflows list.
 *
 * The prose that used to live in `description` (and now lives here): each of the
 * seven modes has its own prompt builder below, carrying that mode's augmentations
 * — author-trust gate, verify-gate opt-in, user-feedback extra-scrutiny preamble,
 * phase-1 slice scoping, next-available-version coordination, triage.auto_close
 * policy, decompose fan-out cap — and every stage validates its worker's return
 * against `workerReturnSchema`. The caller pre-provisions each worker's isolated
 * worktree and passes it in as the work unit's `worktreePath`, because the
 * Dynamic Workflows runtime exposes no isolation primitive of its own (see the
 * "Worktree isolation" section above).
 *
 * The same boundary rejects a few other things this script must keep avoiding:
 * `Date.now()`, `Math.random()`, and argless `new Date()` anywhere in the script
 * (nondeterminism), and TypeScript annotations (the runtime executes plain
 * JavaScript). None are present as of #809; the test suite above covers `meta`
 * specifically, and the nondeterminism/TS constraints are documented here so a
 * later edit does not reintroduce them.
 *
 * `args` HANDLING MUST FAIL LOUDLY, NEVER FAIL OPEN (issue #817)
 * -------------------------------------------------------------------------------
 * The original input guards were written to "keep the script runnable in isolation
 * for a dry read" and fell open to empty on anything unexpected:
 *
 *   const input = typeof args === 'object' && args !== null ? args : {}
 *   const selectedIssues = Array.isArray(input.issues) ? input.issues : []
 *   const workUnits = selectedIssues.map(...)      // pure map, no filter
 *
 * That is reasonable for a bare dry read and actively harmful on the live dispatch
 * path. `args` is UNTYPED at the tool boundary, and the `Workflow` tool's own docs
 * warn that passing a stringified payload is easy to do by accident ("Pass arrays/
 * objects as actual JSON values in the tool call, NOT as a JSON-encoded string").
 * Issue #823 found that remediation does not hold up in practice on this harness:
 * across two separate live dispatches — one pre-#817-fix, one post — `args` arrived
 * JSON-stringified even though the caller passed an actual JSON object in the tool
 * call, not a quoted string. `args` MAY therefore arrive stringified regardless of
 * how the caller invoked the tool (the evidence does not establish this holds for
 * every caller or harness version — just that it is not a rare mistake to guard
 * against defensively). Treat the guarded `JSON.parse` below as REQUIRED handling
 * for the normal delivery shape, not politeness for a hypothetical caller typo —
 * a future refactor must not remove or condition it away on the assumption that
 * "callers just need to pass real JSON" will fix a zero-unit dispatch.
 * When `args` arrived as a JSON STRING, `typeof args === 'object'` was false, so
 * `input` became `{}`, `selectedIssues` became `[]`, `workUnits` became `[]`,
 * `parallel([])` resolved instantly, and the run reported SUCCESS with
 * `agent_count: 0` in 37ms — no error, no warning, and (because the script emitted
 * no `log()`/`phase()` at all) nothing in `/workflows` or the transcript either. A
 * malformed real dispatch was byte-for-byte indistinguishable from a healthy one.
 *
 * Three properties are now load-bearing and must be preserved by any future edit:
 *   1. A JSON-STRING `args` is tolerated — parsed via a guarded `JSON.parse` before
 *      the object check. Per #823, this is not merely tolerance for an unlikely
 *      caller mistake: `args` has been observed arriving stringified on the normal
 *      dispatch path, so this parse is what makes dispatch work at all, not a
 *      defensive fallback for a typo.
 *   2. `args` PRESENT AND NON-EMPTY but yielding ZERO work units THROWS, naming the
 *      received shape (`typeof args`, whether `issues` was an array, its length,
 *      and any JSON-parse failure). A dispatch asked to do work that resolves to
 *      zero units is a caller bug and must surface as an error. The harmless
 *      no-args dry read is preserved: the distinction is "no args at all" (fine)
 *      vs "args given but unusable" (throw).
 *   3. Dispatch emits a `log()` naming the unit count and each unit's mode/target,
 *      so an empty or unexpected run is visible in `/workflows` and the transcript
 *      rather than invisible.
 *
 * NOTE ON VERIFICATION — a zero-unit probe cannot prove this file works. An
 * `args.issues: []` smoke test returned `[]` on BOTH the healthy and the broken
 * path, which is exactly how #817 survived the post-#809 verification. Any future
 * check of this file must exercise a NON-EMPTY unit list and a STRING-shaped
 * `args`; `scripts/tests/workflow-args-fail-loud-817.test.sh` executes the script
 * under a harness that does both.
 */

export const meta = {
  name: 'do-work-dispatch',
  description: 'The /shipyard:do-work dispatch loop as a Dynamic Workflow: an alternate substrate (Agent-tool dispatch is the default, #825) for all seven mode-driven workers (issue-work, fix-checks-only, fix-rebase, fix-main-ci, fix-failing-prs-batch, investigate, spike). The caller pre-provisions each worker isolated worktree and passes it in as worktreePath.',
}

// ---------------------------------------------------------------------------
// Invocation input (injected by the orchestrator via the `args` global).
// The orchestrator — NOT this script — decides these, applying shipyard's
// prioritization + gate-label exclusion + author-trust + blocked-by sequencing.
//
// The defaults below keep the script runnable in isolation for a BARE dry read
// (no `args` at all) and nothing more. Anything that looks like a real dispatch
// but cannot be turned into work units is a caller bug and throws — see the
// file-header "`args` HANDLING MUST FAIL LOUDLY" note (issue #817).
// ---------------------------------------------------------------------------

// `typeof args` is the only safe way to touch `args` — a bare reference to an
// undeclared identifier is a ReferenceError, and a manual dry read may not
// declare it at all.
const rawArgsSupplied = typeof args === 'undefined' ? null : args

// (1) Tolerate a JSON-STRING `args`. The `Workflow` tool's docs explicitly warn
// that a stringified payload is an easy caller mistake, and `args` is untyped at
// the tool boundary, so this is a realistic and recurring shape — not an exotic
// one. Guarded: a parse failure is REMEMBERED (and reported in the throw below)
// rather than swallowed.
let argsJsonParseError = null
let normalizedArgs = rawArgsSupplied
if (typeof normalizedArgs === 'string') {
  const trimmedArgs = normalizedArgs.trim()
  if (trimmedArgs === '') {
    normalizedArgs = null
  } else {
    try {
      normalizedArgs = JSON.parse(trimmedArgs)
    } catch (parseErr) {
      argsJsonParseError = parseErr && parseErr.message ? parseErr.message : String(parseErr)
      normalizedArgs = null
    }
  }
}

// Was a real dispatch attempted at all? "No args" (or an explicitly empty
// object/string) is the harmless dry read; anything else is a dispatch that MUST
// resolve to at least one work unit.
const argsWereSupplied = rawArgsSupplied !== null && rawArgsSupplied !== undefined
const argsAreNonEmpty =
  argsWereSupplied &&
  (typeof rawArgsSupplied === 'string'
    ? rawArgsSupplied.trim() !== ''
    : typeof rawArgsSupplied === 'object'
      ? Object.keys(rawArgsSupplied).length > 0
      : true)

const input = typeof normalizedArgs === 'object' && normalizedArgs !== null ? normalizedArgs : {}
const repo = input.repo ?? '<owner/repo>'
const concurrency = Math.max(1, Number(input.concurrency ?? 1)) // --concurrency N; runtime caps at 16

// (3) `log` is a workflow-runtime global. Guard it with a `typeof` check so a
// manual dry read (or a runtime that doesn't expose it) degrades to a no-op
// instead of a ReferenceError.
const emit = (message) => {
  // eslint-disable-next-line no-undef -- `log` is a workflow-runtime global (see header)
  if (typeof log === 'function') log(message)
}

// Per-work-unit shape (issue-work fields documented alongside the builder below):
//   { number, mode, model, trust, branch, worktreePath,
//     pluginRoot, pluginRootStale, skillCacheStale,
//     verifyGate, userFeedback, splitDispatch, phase1Scope, bundledIssues,
//     sharedSurface, groupingRationale,
//     stalePremisePhrase, stalePremiseCorrection, tokenBudgetWarning, sessionConcurrency,
//     nextAvailableVersion, changelogPath }
const selectedIssues = Array.isArray(input.issues) ? input.issues : []

// Per-role model map, mirroring resolve-dispatch-model.sh's tiering. Passed in so
// the substrate stays config-driven rather than hardcoding model ids here.
const models = input.models ?? {}

// The structured-return contract every stage validates against. This is the shape
// of schemas/worker-return.schema.json — the workflow runtime validates each
// agent() result against `schema`, so a malformed return fails at the stage
// boundary instead of being re-parsed from prose (the free-text return-string
// convention this replaces for workflow-dispatched workers only). Kept as a literal
// copy (not a `require`/`import` of the JSON file) because the workflow runtime
// executes this script in an isolated environment with no filesystem access of its
// own — see the "Worktree isolation" note above for the same constraint applied to
// worker dispatch; this also means full de-duplication (importing the JSON file
// directly) is not an option here, unlike a normal Node module. Keep this object's
// `enum`/`required`/`additionalProperties`/`allOf`/`minimum` shape in sync with
// schemas/worker-return.schema.json by hand on any return-contract change — field
// `description`s are NOT required to match (this copy omits them entirely; they
// carry no validation weight). A drift on any of those validation-relevant facets
// is caught mechanically by scripts/check-worker-return-schema-parity.mjs (run via
// scripts/tests/worker-return-schema-parity-856.test.sh in CI), which diffs this
// literal against the canonical JSON schema field-for-field — so "review both files
// together" is now a backstop, not the only line of defense (issue #856: the
// `allOf` conditional-required block and `issue`/`pr`'s `minimum: 1` had drifted
// out of this copy silently, with nothing catching it).
const workerReturnSchema = {
  type: 'object',
  required: ['mode', 'outcome'],
  additionalProperties: false,
  properties: {
    mode: {
      type: 'string',
      enum: [
        'issue-work',
        'fix-checks-only',
        'fix-rebase',
        'fix-main-ci',
        'fix-failing-prs-batch',
        'investigate',
        'spike',
      ],
    },
    outcome: {
      type: 'string',
      enum: [
        'shipped',
        'green',
        'pending',
        'dirty',
        'rebased',
        'noop',
        'blocked',
        'reaped',
        'disposition',
        'awaiting-external',
      ],
    },
    issue: { type: ['integer', 'null'], minimum: 1 },
    pr: { type: ['integer', 'null'], minimum: 1 },
    incidental_pr: { type: ['integer', 'null'], minimum: 1 },
    auto_merge: {
      type: ['string', 'null'],
      enum: [
        'enabled',
        'gated-manual',
        'merged-direct',
        'merged-direct-ungated',
        'unavailable',
        'unavailable-workflow-scope',
        'gated-external',
        'unarmed-policy-override',
        'unarmed-gate-narrowing',
        null,
      ],
    },
    policy_override: { type: ['string', 'null'] },
    gate_narrowing: { type: ['string', 'null'] },
    awaiting_what: { type: ['string', 'null'] },
    awaiting_probe: { type: ['string', 'null'] },
    awaiting_eta: { type: ['string', 'null'] },
    checks: { type: ['string', 'null'], enum: ['green', 'pending', 'failing', null] },
    head_sha: { type: ['string', 'null'] },
    disposition: {
      type: ['string', 'null'],
      enum: ['fix', 'needs-human-review', 'auto-close-noise', 'duplicate', 'verified', null],
    },
    blocked_reason: { type: ['string', 'null'] },
    blocked_stage: { type: ['string', 'null'] },
    last_push: { type: ['string', 'null'] },
    worktree_path: { type: ['string', 'null'] },
    summary: { type: ['string', 'null'] },
  },
  allOf: [
    {
      // A blocked outcome must carry a reason.
      if: { properties: { outcome: { const: 'blocked' } } },
      then: { required: ['blocked_reason'] },
    },
    {
      // A disposition outcome must name how it dispositioned.
      if: { properties: { outcome: { const: 'disposition' } } },
      then: { required: ['disposition'] },
    },
    {
      // An awaiting-external outcome must name the job AND the probe the orchestrator will run (#1390).
      if: { properties: { outcome: { const: 'awaiting-external' } } },
      then: { required: ['awaiting_what', 'awaiting_probe'] },
    },
    {
      // An unarmed-policy-override auto_merge value must name the overridden control (#1088).
      if: { properties: { auto_merge: { const: 'unarmed-policy-override' } } },
      then: { required: ['policy_override'] },
    },
    {
      // An unarmed-gate-narrowing auto_merge value must name the tripped signal (#1139).
      if: { properties: { auto_merge: { const: 'unarmed-gate-narrowing' } } },
      then: { required: ['gate_narrowing'] },
    },
  ],
}

// ---------------------------------------------------------------------------
// STAGE 1 — SELECT.
// The orchestrator pre-computes the selection (including, per mode, the
// author-trust resolution, spike-shape exclusion, phase-1 slice, verify-gate
// flag, user-feedback flag, version-coordination paragraph, triage.auto_close
// policy, and decompose.max_subissues cap) and injects it via `args.issues`;
// this stage normalizes it into the unit-of-work list the pipeline fans out
// over. Selection POLICY itself stays in the orchestrator, not this script —
// see the file-header "What stays out of this script" note.
// ---------------------------------------------------------------------------
const workUnits = selectedIssues.map((it) => ({
  number: it.number ?? null, // null for synthetic diverts (fix-main-ci, fix-failing-prs-batch)
  mode: it.mode ?? 'issue-work',
  model: it.model ?? models[it.mode ?? 'issue-work'],
  trust: it.trust ?? 'external', // conservative default; orchestrator normally sets this
  branch: it.branch ?? (it.number != null ? `do-work/issue-${it.number}` : null),
  worktreePath: it.worktreePath ?? null, // REQUIRED for every mode — see header note
  // Every-mode worktree-anchor inputs (#969 / #1319), read by shared.mjs's
  // worktreeAnchorLines. Every field a prompt builder reads MUST be copied here —
  // an omitted one is silently dropped and its paragraph never renders (#1615;
  // workflow-unit-field-passthrough-1615.test.sh enforces this).
  pluginRoot: it.pluginRoot ?? null,
  pluginRootStale: it.pluginRootStale ?? null,
  skillCacheStale: it.skillCacheStale ?? null,
  // issue-work-only augmentations
  verifyGate: it.verifyGate === true,
  userFeedback: it.userFeedback === true,
  splitDispatch: it.splitDispatch === true, // #1562 neutral-branch paragraph
  phase1Scope: it.phase1Scope ?? null,
  bundledIssues: Array.isArray(it.bundledIssues) ? it.bundledIssues : [], // #1596 co-scoped bundle paragraph
  sharedSurface: it.sharedSurface ?? null,
  groupingRationale: it.groupingRationale ?? null,
  stalePremisePhrase: it.stalePremisePhrase ?? null, // #1491 stale-premise paragraph
  stalePremiseCorrection: it.stalePremiseCorrection ?? null,
  tokenBudgetWarning: it.tokenBudgetWarning ?? null,
  sessionConcurrency: concurrency, // #1594 concurrent-tenant paragraph, rendered when > 1
  nextAvailableVersion: it.nextAvailableVersion ?? null,
  changelogPath: it.changelogPath ?? null,
  // fix-checks-only / fix-rebase — target an EXISTING PR's branch, not a fresh one
  pr: it.pr ?? null,
  headRefName: it.headRefName ?? null,
  versionCoordinationParagraph: it.versionCoordinationParagraph ?? null, // fix-rebase §4.6 carve-out
  ciPoolState: it.ciPoolState ?? null, // #1609 fix-checks-only contention probe (self-hosted pool only)
  // fix-main-ci — synthetic divert, no originating issue
  earliestRedRunUrl: it.earliestRedRunUrl ?? null,
  earliestRedSha: it.earliestRedSha ?? null,
  // fix-failing-prs-batch — synthetic divert, no originating issue
  failingPrCountAll: it.failingPrCountAll ?? null,
  failingPrNumbers: it.failingPrNumbers ?? null,
  // investigate
  triageAutoClose: it.triageAutoClose ?? 'confident-only',
  // spike
  decomposeMaxSubissues: it.decomposeMaxSubissues ?? 8,
}))

// ---------------------------------------------------------------------------
// (2) FAIL LOUDLY, NEVER FAIL OPEN (issue #817). A dispatch that was ASKED to do
// work but resolved to zero work units is a caller bug — it must never be
// reported as an empty success. The harmless bare dry read (no `args` at all) is
// deliberately preserved as the one zero-unit path that does not throw.
// ---------------------------------------------------------------------------
if (workUnits.length === 0) {
  if (argsAreNonEmpty) {
    const receivedShape = [
      `typeof args = ${typeof rawArgsSupplied}`,
      argsJsonParseError
        ? `JSON.parse of the string-shaped args FAILED: ${argsJsonParseError}`
        : typeof rawArgsSupplied === 'string'
          ? 'the string-shaped args parsed successfully'
          : 'args was not string-shaped (no JSON.parse attempted)',
      `args.issues is ${Array.isArray(input.issues) ? 'an array' : `NOT an array (typeof ${typeof input.issues})`}`,
      `args.issues length = ${Array.isArray(input.issues) ? input.issues.length : 'n/a'}`,
      `top-level keys = ${
        typeof input === 'object' && input !== null ? JSON.stringify(Object.keys(input)) : 'n/a'
      }`,
    ].join('; ')

    throw new Error(
      `do-work-dispatch: refusing to report an empty dispatch as success — args were supplied but resolved to ZERO work units. ` +
        `Received: ${receivedShape}. ` +
        `Verify args.issues is a NON-EMPTY array of work units, with each unit carrying at least a mode and a ` +
        `worktreePath (or args itself is a JSON string encoding such an array). Re-shaping the tool call as a ` +
        `literal object instead of a JSON string will NOT by itself fix this — args commonly arrives ` +
        `JSON-stringified at this tool boundary regardless of how it was passed, so an empty or malformed ` +
        `issues array is a caller-side selection bug, not a JSON-encoding mistake. See issues #817, #823.`,
    )
  }

  // No args at all — the harmless dry read. Say so, so even this path is visible.
  emit('do-work-dispatch: no args supplied — dry read, dispatching 0 workers.')
}

// (3) Make the dispatch visible in /workflows and the transcript. The script
// previously emitted NO log()/phase() at all, which is precisely why the empty
// run in #817 was invisible everywhere.
if (workUnits.length > 0) {
  emit(
    `do-work-dispatch: dispatching ${workUnits.length} work unit(s) against ${repo} ` +
      `(concurrency ${concurrency}): ${workUnits.map(unitLabel).join(', ')}`,
  )
}

// ---------------------------------------------------------------------------
// STAGE 2 — DISPATCH one worker per unit, sequentially.
//
// Each worker runs the SAME per-mode lifecycle it runs today (implement → verify →
// open-PR / arm-merge), driven by the per-mode spec in agents/issue-worker/<mode>.md
// via the worker-preamble skill. The workflow's contribution is the schema-validated
// return + building the exact same dispatch prompt the Agent-tool path builds for
// that mode — see the per-mode `build<Mode>Prompt` helpers below.
//
// No in-script fan-out primitive is used here (issue #888) — `workUnits` is a
// one-element array on the live path (this script is invoked ONCE PER WORK UNIT
// by the orchestrator's own `--concurrency N` rolling pool, mirroring one `Agent`
// call per pool slot; see "Concurrency model" in the file header). The loop below
// simply awaits `dispatchWorker` for each unit in turn — on the live single-unit
// path that's one iteration; a manual dry run passing more than one unit gets
// them dispatched one after another rather than concurrently, which is fine
// since nothing exercises multi-unit args on the real dispatch path.
// ---------------------------------------------------------------------------
const dispatchWorker = (unit) =>
  agent(buildWorkerPrompt(unit, repo), {
    label: unitLabel(unit),
    model: unit.model, // per-mode tier from resolve-dispatch-model.sh, injected via args
    schema: workerReturnSchema, // structured return validated at the stage boundary
  })

const results = []
for (const unit of workUnits) {
  results.push(await dispatchWorker(unit))
}

// ---------------------------------------------------------------------------
// STAGE 3 — COLLECT.
// Hand the schema-validated structured results back to the orchestrator's reconcile,
// which owns the state transitions (session_prs, failed_prs, deferred_issues, the
// blocked-reason → label classification per #521, cost bump-tokens). The workflow
// does NOT reconcile — it produces the validated results the reconcile consumes.
// The caller translates each result object into the existing free-text return-string
// vocabulary before handing it to steady-state.md's step A.1 parser, so every
// downstream reconcile branch runs completely unchanged — see dispatch-rules.md's
// substrate section for the translation table.
// ---------------------------------------------------------------------------
return results.filter(Boolean)

// ===========================================================================
// Helper — the human-readable "mode/target" name for one work unit. Used both
// as the `agent()` label in the /workflows progress view AND in the dispatch
// `log()` line (issue #817), so the two can never drift apart. Synthetic diverts
// (fix-main-ci, fix-failing-prs-batch) have no issue number — fall back to the
// target PR (fix-checks-only/fix-rebase) or a bare mode name.
// ===========================================================================
function unitLabel(unit) {
  if (unit.number != null) return `${unit.mode} #${unit.number}`
  if (unit.pr != null) return `${unit.mode} PR#${unit.pr}`
  return unit.mode
}

// ===========================================================================
// Helper — build the per-worker dispatch prompt. Routes to a mode-specific
// builder; all seven `mode:` values have a real implementation as of #789
// (phase 3). An unrecognized mode falls through to a defensive placeholder —
// that branch should be unreachable via dispatch-rules.md's routing and only
// matters for a manual dry run of the script against a malformed unit.
//
// Each builder — SOURCED from workflows/prompt-templates/*.mjs and inlined
// here by the generator (see this file's header, issue #958) — is the
// workflow-substrate twin of dispatch-rules.md's reviewable prose template
// for the same mode — NOT byte-identical by design (this shape additionally
// needs the worktree-anchor preamble and a structured-return-contract
// closing dispatch-rules.md's Agent-tool prose doesn't), but the mode
// inventory, `agents/issue-worker/<mode>.md` spec-file references, and
// conditional augmentation paragraphs (verify-gate / user-feedback /
// phase-1-slice / next-available-version) must stay in sync. "Review both
// files together" used to be the only enforcement of that, and it silently
// failed (issue #880: the user-feedback preamble was missing dispatch-
// rules.md's trailing "misread the user" clause). A drift on any of those
// facets is now caught mechanically by scripts/check-dispatch-prompt-parity.
// mjs (run via scripts/tests/dispatch-prompt-parity-880.test.sh in CI) —
// the same "hand-copied content drifts silently, add a mechanical parity
// checker" remedy #856 applied to the worker-RETURN schema just below,
// applied here to the worker-DISPATCH prompt half of the same problem. That
// checker parses the GENERATED do-work-dispatch.workflow.js (not these
// source fragments), so it keeps working unmodified across the #958 split.
// ===========================================================================
function buildWorkerPrompt(unit, repoSlug) {
  switch (unit.mode) {
    case 'issue-work':
      return buildIssueWorkPrompt(unit, repoSlug)
    case 'fix-checks-only':
      return buildFixChecksOnlyPrompt(unit, repoSlug)
    case 'fix-rebase':
      return buildFixRebasePrompt(unit, repoSlug)
    case 'fix-main-ci':
      return buildFixMainCiPrompt(unit, repoSlug)
    case 'fix-failing-prs-batch':
      return buildFixFailingPrsBatchPrompt(unit, repoSlug)
    case 'investigate':
      return buildInvestigatePrompt(unit, repoSlug)
    case 'spike':
      return buildSpikePrompt(unit, repoSlug)
    default:
      return [
        `mode: ${unit.mode}`,
        ``,
        `CALLER BUG: "${unit.mode}" is not a recognized do-work worker mode for the`,
        `workflow substrate. This branch should be unreachable via dispatch-rules.md's`,
        `routing — if you're reading this, either a new mode was added to the routing`,
        `table without a matching builder here, or this is a manual dry run against a`,
        `malformed unit. Return a STRUCTURED result immediately:`,
        `{ "mode": "${unit.mode}", "outcome": "blocked",`,
        `"blocked_reason": "unrecognized mode passed to do-work-dispatch.workflow.js" }.`,
        `Do not proceed past this line.`,
      ].join('\n')
  }
}
