#!/usr/bin/env bash
# Test: the config-declared generated-file regeneration carve-out in
# fix-rebase mode, and its known-rewrites recording (issue #1445).
#
# Background — issue #1445: fix-rebase.md's step 4 already told the worker
# to resolve a lockfile conflict by RE-RUNNING THE GENERATOR (the package
# manager) rather than hand-merging — correct, since a lockfile's content is
# a pure function of the tree and has no meaningful hand-merge. But
# regeneration necessarily replaces the file's content with freshly computed
# values that no longer match what the PR's own commit(s) originally added,
# which is exactly what step 5.8's line-survival guard
# (verify-added-lines-survived.sh, issue #983) is built to flag as
# corruption. Before this fix, the ONLY sanctioned known-rewrites exemption
# (issue #1215) was scoped to §4.6's version-coordination case — a per-LINE
# exemption for exactly two lines (a manifest `.version` row and a CHANGELOG
# heading). A regenerated content-hash manifest has no fixed, enumerable
# "the one line that changed" the way a version row does — potentially every
# line differs — so the per-line mechanism can't express "this whole file
# was legitimately regenerated." The result, reproduced live in session
# do-work-20260817T182449Z-33530 against mattsears18/lightwork PR #4223: the
# worker correctly regenerated a conflicted content-hash manifest
# (`content-updated.generated.json`) per the spec's own guidance, and step
# 5.8 then discarded the correct resolution as CORRUPTED — turning a
# mechanically-resolvable rebase into stranded human work.
#
# The fix has two parts:
#   1. verify-added-lines-survived.sh gains a whole-file exemption shape: a
#      3-field known-rewrites TSV entry (`<path>\tFILE\t<reason>`) exempts
#      the named path's added-line comparison entirely, while its
#      file-existence check (and every OTHER touched file's full
#      comparison) is unaffected. See verify-added-lines-survived.test.sh
#      for the script's own direct behavioral tests of this shape.
#   2. fix-rebase.md gains a new §4.7 recipe: for a conflict resolved by
#      regenerating either one of the four canonical lockfiles OR a path
#      explicitly listed in the new `version_coordination.generated_paths`
#      config (array of {path, command} — mirrors `append_only_paths`'s
#      independence from `version_coordination.enabled`), record a
#      whole-file known-rewrites entry in the SAME
#      `.shipyard-scratch/vc-known-rewrites.tsv` file §4.6 item 5 already
#      uses, so step 5.8 exempts it without any change to its own
#      invocation.
#
# `generated_paths` is deliberately an explicit per-path allowlist, not a
# glob or a filename heuristic (e.g. `*.generated.*`) — a repo maintainer
# opts a path in and states exactly how to regenerate it, so a file that
# merely LOOKS generated by name, but that the worker actually hand-edited,
# is never silently exempted. The guard stays default-deny for every path
# not explicitly registered.
#
# This test pins THREE layers:
#   (A) Config/schema — the schema declares `generated_paths` (array of
#       {path, command} objects, default `[]`), the built-in default is
#       `[]`.
#   (B) Spec assertions — fix-rebase.md links to #1445, broadens the
#       Lockfiles bullet, adds §4.7, reads `generated_paths`, and the
#       known-rewrites scratch file is initialized exactly once (never
#       re-truncated by either §4.6 item 5 or §4.7).
#   (C) Behavioral — reconstruct the PR-#4223 shape (a generated JSON
#       manifest conflicts and is resolved by regeneration, unrelated to any
#       manifest/CHANGELOG coordination) using real git, and confirm the
#       whole-file known-rewrites entry produced per §4.7's recipe makes
#       verify-added-lines-survived.sh pass clean on the regenerated
#       content while still catching real corruption in an untouched file.
#
# Pure bash + git + jq. Run with:
#
#   bash plugins/shipyard/scripts/tests/fix-rebase-generated-files.test.sh

set -u

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$here"
while [[ "$repo_root" != "/" ]]; do
  if [[ -d "$repo_root/.git" || -f "$repo_root/CHANGELOG.md" ]]; then
    break
  fi
  repo_root="$(dirname "$repo_root")"
done

if [[ "$repo_root" == "/" ]]; then
  echo "FAIL: could not locate repo root from $here" >&2
  exit 1
fi

fix_rebase="$repo_root/plugins/shipyard/agents/issue-worker/fix-rebase.md"
schema="$repo_root/plugins/shipyard/schemas/shipyard.config.schema.json"
config_helper="$repo_root/plugins/shipyard/scripts/shipyard-config.sh"
survived_script="$repo_root/plugins/shipyard/scripts/verify-added-lines-survived.sh"

pass=0
fail=0
GREEN=$'\033[32m'; RED=$'\033[31m'; RESET=$'\033[0m'

ok()  { printf '  %sPASS%s  %s\n' "$GREEN" "$RESET" "$1"; pass=$((pass+1)); }
bad() { printf '  %sFAIL%s  %s\n' "$RED" "$RESET" "$1"; fail=$((fail+1)); }

assert_contains() {
  local file="$1" needle="$2" label="$3"
  if grep -qF -- "$needle" "$file" 2>/dev/null; then
    ok "$label"
  else
    bad "$label (expected in $file: $needle)"
  fi
}

echo "fix-rebase generated-file regeneration carve-out tests (issue #1445)"
echo

# ---------------------------------------------------------------------------
# (A) Config/schema.
# ---------------------------------------------------------------------------

if [[ -f "$schema" ]]; then
  assert_contains "$schema" '"generated_paths"' \
    "schema declares version_coordination.generated_paths"
  assert_contains "$schema" 'issue #1445' \
    "schema description links to issue #1445"
  assert_contains "$schema" '"required": ["path", "command"]' \
    "schema requires path+command on each generated_paths entry"
fi

if [[ -f "$config_helper" ]] && command -v jq >/dev/null 2>&1; then
  home="$(mktemp -d)"
  fresh_repo="$(mktemp -d)"
  out=$(SHIPYARD_REPO_ROOT="$fresh_repo" SHIPYARD_HOME="$home" "$config_helper" get version_coordination.generated_paths 2>&1)
  if [[ "$out" == "[]" ]]; then
    ok "default version_coordination.generated_paths is [] on a repo with no config"
  else
    bad "default version_coordination.generated_paths: expected [], got: $out"
  fi
  rm -rf "$home" "$fresh_repo"
fi

# ---------------------------------------------------------------------------
# (B) Spec assertions.
# ---------------------------------------------------------------------------

if [[ -f "$fix_rebase" ]]; then
  assert_contains "$fix_rebase" 'issues/1445' \
    "fix-rebase.md links to originating issue #1445"
  assert_contains "$fix_rebase" 'Lockfiles and other config-declared generated files' \
    "fix-rebase.md broadens the Lockfiles bullet to generated files generally"
  assert_contains "$fix_rebase" '#### 4.7. Lockfile/generated-file regeneration' \
    "fix-rebase.md adds a §4.7 recipe for known-rewrites recording"
  assert_contains "$fix_rebase" 'version_coordination.generated_paths' \
    "fix-rebase.md reads version_coordination.generated_paths"
  assert_contains "$fix_rebase" 'never a glob or a filename heuristic' \
    "fix-rebase.md documents generated_paths as an explicit allowlist, not a glob/heuristic"
  assert_contains "$fix_rebase" 'printf '"'"'%s\tFILE\tregenerated via %s\n'"'"'' \
    "fix-rebase.md's §4.7 recipe writes a 3-field FILE-kind known-rewrites entry"
  # The scratch file must be initialized exactly once, before either §4.6
  # item 5 or §4.7 can write to it — never re-truncated by either recipe.
  assert_contains "$fix_rebase" 'the ONE truncation point per dispatch' \
    "fix-rebase.md documents a single known-rewrites truncation point shared by §4.6 and §4.7"
  assert_contains "$fix_rebase" 'only ever APPENDS, never re-truncates' \
    "fix-rebase.md's §4.6 item 5 recipe appends rather than re-truncating the known-rewrites file"

  # Issue #1611: a value-only conflict on a path NOT in generated_paths must
  # bail with text naming the missing declaration, not the generic
  # "needs human merge judgment" reason — and must stay a bail.
  assert_contains "$fix_rebase" 'issues/1611' \
    "fix-rebase.md links to issue #1611 (value-only conflict recognition)"
  assert_contains "$fix_rebase" 'Value-only conflict on an undeclared path' \
    "fix-rebase.md step 4 adds the value-only recognition check before the generic bail"
  assert_contains "$fix_rebase" 'declare each one in version_coordination.generated_paths with its regeneration command' \
    "fix-rebase.md's value-only bail text names the generated_paths declaration as the remedy"
  assert_contains "$fix_rebase" 'no human merge judgment is required for that route' \
    "fix-rebase.md's value-only bail text says no human merge judgment is required"
  assert_contains "$fix_rebase" 'This stays a bail, never an auto-resolve.' \
    "fix-rebase.md keeps the value-only recognition a bail, not an auto-resolve"
fi

steady_state="$repo_root/plugins/shipyard/commands/do-work/steady-state.md"
if [[ -f "$steady_state" ]]; then
  assert_contains "$steady_state" 'Needs a generated_paths declaration, not a manual rebase.' \
    "steady-state.md's blocked-rebase comment does not say 'Needs manual rebase.' for the #1611 sub-case"
fi

# ---------------------------------------------------------------------------
# (C) Behavioral — reconstruct the PR #4223 shape: a generated JSON manifest
# conflicts and is resolved by regeneration; verify-added-lines-survived.sh
# must pass clean on the regenerated content (via the §4.7 whole-file
# known-rewrites entry) while still catching real corruption in an
# unrelated, untouched file in the same PR.
# ---------------------------------------------------------------------------

if [[ -f "$survived_script" ]] && command -v git >/dev/null 2>&1; then
  work="$(mktemp -d)"
  trap 'rm -rf "$work"' EXIT

  repo="$work/repo"
  mkdir -p "$repo"
  git -C "$repo" init -q -b main
  git -C "$repo" config user.email "test@example.com"
  git -C "$repo" config user.name "Test"

  # base: a generated content-hash manifest and an unrelated source file.
  printf '{"hash":"base"}\n' > "$repo/content-updated.generated.json"
  printf 'export const x = 1;\n' > "$repo/other.ts"
  git -C "$repo" add content-updated.generated.json other.ts
  git -C "$repo" commit -q -m base
  base_sha="$(git -C "$repo" rev-parse HEAD)"

  # feature (the PR): regenerates the manifest with its own hash, AND adds a
  # genuine, non-generated line to other.ts.
  git -C "$repo" checkout -q -b feature
  printf '{"hash":"feature-abc"}\n' > "$repo/content-updated.generated.json"
  printf 'export const x = 1;\nexport const y = 2;\n' > "$repo/other.ts"
  git -C "$repo" add content-updated.generated.json other.ts
  git -C "$repo" commit -q -m "feature: geo field + manifest regen"
  feature_sha="$(git -C "$repo" rev-parse HEAD)"

  # main: advances independently — a sibling PR also regenerated the
  # manifest (different hash) and is unrelated to other.ts.
  git -C "$repo" checkout -q main
  printf '{"hash":"main-xyz"}\n' > "$repo/content-updated.generated.json"
  git -C "$repo" add content-updated.generated.json
  git -C "$repo" commit -q -m "main advanced: manifest regenerated by sibling PR"

  known_rewrites="$work/known-rewrites.tsv"
  printf 'content-updated.generated.json\tFILE\tregenerated via node scripts/generate-content-updated.mjs\n' > "$known_rewrites"

  # ── (C1) Post-rebase result: manifest re-regenerated (fresh hash, shares
  # NOTHING with what the PR's commit originally added), other.ts's real
  # added line ('export const y = 2;') genuinely survived. With the §4.7
  # whole-file exemption, this must pass clean. ─────────────────────────────
  git -C "$repo" checkout -q -b rebased-regenerated-clean main
  printf '{"hash":"rebased-final-regen"}\n' > "$repo/content-updated.generated.json"
  printf 'export const x = 1;\nexport const y = 2;\n' > "$repo/other.ts"
  git -C "$repo" add content-updated.generated.json other.ts
  git -C "$repo" commit -q -m "rebased: manifest re-regenerated, other.ts intact"

  out="$(cd "$repo" && bash "$survived_script" "$base_sha" "$feature_sha" "$known_rewrites" 2>&1)"
  status=$?
  if [[ $status -eq 0 && "$out" == OK:* ]]; then
    ok "PR #4223 repro: re-regenerated content-hash manifest exempted, exit 0 OK (other.ts's real added line still verified present)"
  else
    bad "PR #4223 repro: expected exit 0 + OK, got exit $status: $out"
  fi

  # ── (C2) Same regenerated tree WITHOUT the §4.7 exemption must fail —
  # confirms (C1) passed BECAUSE of the exemption (this is the exact
  # pre-fix failure mode: the worker's correct regeneration gets discarded
  # as CORRUPTED). ────────────────────────────────────────────────────────
  out="$(cd "$repo" && bash "$survived_script" "$base_sha" "$feature_sha" 2>&1)"
  status=$?
  if [[ $status -eq 1 && "$out" == CORRUPTED:*content-updated.generated.json* ]]; then
    ok "PR #4223 repro baseline: without §4.7's exemption, the correctly-regenerated manifest is (pre-fix) flagged CORRUPTED"
  else
    bad "PR #4223 repro baseline: expected exit 1 + CORRUPTED:...content-updated.generated.json..., got exit $status: $out"
  fi

  # ── (C3) The exemption must not mask real corruption of other.ts's own
  # added line in the same rebase. ───────────────────────────────────────
  git -C "$repo" checkout -q -b rebased-regenerated-other-corrupted main
  printf '{"hash":"rebased-final-regen-2"}\n' > "$repo/content-updated.generated.json"
  printf 'export const x = 1;\n' > "$repo/other.ts"   # 'export const y = 2;' dropped
  git -C "$repo" add content-updated.generated.json other.ts
  git -C "$repo" commit -q -m "rebased: manifest regenerated (fine), other.ts corrupted"

  out="$(cd "$repo" && bash "$survived_script" "$base_sha" "$feature_sha" "$known_rewrites" 2>&1)"
  status=$?
  if [[ $status -eq 1 && "$out" == CORRUPTED:*other.ts* && "$out" != *content-updated.generated.json* ]]; then
    ok "PR #4223 repro: exemption does not mask corruption in the sibling other.ts file"
  else
    bad "PR #4223 repro: expected exit 1 + CORRUPTED:...other.ts... (no manifest), got exit $status: $out"
  fi
fi

echo
if (( fail > 0 )); then
  printf '%sFAIL%s  %d test(s) failed (%d passed)\n' "$RED" "$RESET" "$fail" "$pass" >&2
  exit 1
else
  printf '%sPASS%s  all %d test(s) passed\n' "$GREEN" "$RESET" "$pass"
  exit 0
fi
